export const APP_READY = "APP_READY";

export const PREFERENCES_SET = "PREFERENCES_SET";
export const PREFERENCES_RESET = "PREFERENCES_RESET";

export const SWARM_LOADING_START = "SWARM_LOADING_START";
export const SWARM_LOADING_DONE = "SWARM_LOADING_DONE";
export const SWARM_DATA_RECEIVED = "SWARM_DATA_RECEIVED";
export const SWARM_UPDATE_RECEIVED = "SWARM_UPDATE_RECEIVED";
export const SWARM_CLEAR_DATA = "SWARM_CLEAR_DATA";
export const SWARM_DELETE_NESTED_DATA = "SWARM_DELETE_NESTED_DATA";
export const SWARM_DATA_BET_HISTORY_UNSETTLED_UPDATE_RECEIVED = "SWARM_DATA_BET_HISTORY_UNSETTLED_UPDATE_RECEIVED";
export const DESTROY_LOADED_BET_HISTORY = "DESTROY_LOADED_BET_HISTORY";

export const SWARM_CONFIG_DATA = "SWARM_CONFIG_DATA";

export const DISCONNECTED = "DISCONNECTED";
export const CONNECTED = "CONNECTED";

export const LOGIN_START = "LOGIN_START";
export const LOGGED_IN = "LOGGED_IN";                   // login state in UI
export const REALLY_LOGGED_IN = "REALLY_LOGGED_IN";     // the real login state
export const LOGGED_OUT = "LOGOUT";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SESSION_LOST = "SESSION_LOST";
export const SESSION_ACTIVE = "SESSION_ACTIVE";

export const USER_PROFILE_UPDATE_RECEIVED = "USER_PROFILE_UPDATE_RECEIVED";

export const POOL_BETTING_TOKEN_LOADED = "POOL_BETTING_TOKEN_LOADED";
export const POOL_BETTING_TOKEN_LOADING = "POOL_BETTING_TOKEN_LOADING";
export const POOL_BETTING_TOKEN_FAILED = "POOL_BETTING_TOKEN_FAILED";

//persistent UI
export const PREMATCH_TIME_FILTER = "PREMATCH_TIME_FILTER";
export const LIVE_VIDEO_FILTER = "LIVE_VIDEO_FILTER";
export const PREMATCH_WIDGET_TIME_FILTER = "PREMATCH_WIDGET_TIME_FILTER";
export const UI_EXPAND_ELEMENT = "UI_EXPAND_ELEMENT";
export const UI_COLLAPSE_ELEMENT = "UI_COLLAPSE_ELEMENT";

// non-persistent UI
export const UI_OPEN = "UI_OPEN";
export const UI_CLOSE = "UI_CLOSE";
export const UI_LOADING = "UI_LOADING";
export const UI_LOADING_DONE = "UI_LOADING_DONE";
export const UI_LOADING_FAILED = "UI_LOADING_FAILED";
export const UI_LOADING_RESET = "UI_LOADING_RESET";
export const UI_LAST_ROUTE_TYPE = "UI_LAST_ROUTE_TYPE";
export const UI_PREVIOUS_PATH = "UI_PREVIOUS_PATH";
export const UI_CURRENT_ROUTE_TYPE = "UI_CURRENT_ROUTE_TYPE";
export const SCROLL_TO_SPORT_ALIAS = "SCROLL_TO_SPORT_ALIAS";
export const SCROLLED_TO_SPORT_ALIAS = "SCROLLED_TO_SPORT_ALIAS";

export const OPEN_POPUP = "OPEN_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";

export const CONFIRMATION_DIALOG_ANSWER = "CONFIRMATION_DIALOG_ANSWER";
export const CONFIRMATION_DIALOG_RESET = "CONFIRMATION_DIALOG_RESET";

export const HIDE_ANDROID_APP_DOWNLOAD_POPUP = "HIDE_ANDROID_APP_DOWNLOAD_POPUP";

export const FAVORITE_ADD = "FAVORITE_ADD";
export const FAVORITE_REMOVE = "FAVORITE_REMOVE";
export const FAVORITES_CLEAR = "FAVORITES_CLEAR";
export const SPORTS_FAVORITES_CLEAR = "SPORTS_FAVORITES_CLEAR";
export const CASINO_FAVORITES_CLEAR = "CASINO_FAVORITES_CLEAR";
export const MARKET_FAVORITES_CLEAR = "MARKET_FAVORITES_CLEAR";

export const BETSLIP_ADD = "BETSLIP_ADD";
export const BETSLIP_REMOVE = "BETSLIP_REMOVE";
export const BETSLIP_CLEAR = "BETSLIP_CLEAR";
export const BETSLIP_SET_TYPE = "BETSLIP_SET_TYPE";
export const BETSLIP_ACCEPT_CHANGES = "BETSLIP_ACCEPT_CHANGES";
export const BETSLIP_TOGGLE_QUICKBET = "BETSLIP_TOGGLE_QUICKBET";
export const BETSLIP_TOGGLE_SUPERBET = "BETSLIP_TOGGLE_SUPERBET";
export const BETSLIP_TOGGLE_FREEBET = "BETSLIP_TOGGLE_FREEBET";
export const BETSLIP_BET_ACCEPTED = "BETSLIP_BET_ACCEPTED";
export const BETSLIP_BET_FAILED = "BETSLIP_BET_FAILED";
export const BETSLIP_BET_PROCESSING = "BETSLIP_BET_PROCESSING";
export const BETSLIP_RESET_STATUS = "BETSLIP_RESET_STATUS";
export const BETSLIP_SET_STAKE = "BETSLIP_SET_STAKE";
export const BETSLIP_SET_UNIT_STAKE = "BETSLIP_SET_UNIT_STAKE";
export const BETSLIP_SET_EACH_WAY_MODE = "BETSLIP_SET_EACH_WAY_MODE";
export const BETSLIP_SET_SYSTEM_OPT = "BETSLIP_SET_SYSTEM_OPT";
export const BETSLIP_SET_ACCEPT_OPT = "BETSLIP_SET_ACCEPT_OPT";
export const BETSLIP_TOGGLE_FREEBET_LOADING_STATE = "BETSLIP_TOGGLE_FREEBET_LOADING_STATE";
export const BETSLIP_SET_INCLUDE_IN_SYSTEM_CALC = "BETSLIP_SET_INCLUDE_IN_SYSTEM_CALC";
export const BETSLIP_QUICK_BET_NOTIFY = "BETSLIP_QUICK_BET_NOTIFY";
export const BETSLIP_QUICK_BET_NOTIFY_DISMISS = "BETSLIP_QUICK_BET_NOTIFY_DISMISS";
export const BETSLIP_SET_FREE_BETS = "BETSLIP_SET_FREE_BETS";
export const BETSLIP_SELECT_FREE_BET = "BETSLIP_SELECT_FREE_BET";

export const CMS_LOAD_START = "CMS_LOAD_START";
export const CMS_LOAD_DONE = "CMS_LOAD_DONE";
export const CMS_DATA_RECEIVED = "CMS_DATA_RECEIVED";

// registration captcha
export const CAPTCH_LOAD_SUCCESS = "CAPTCH_LOAD_SUCCESS";
export const CAPTCH_LOAD_FAILURE = "CAPTCH_LOAD_FAILURE";

export const BETSHOP_LOADING_DONE = "BETSHOP_LOADING_DONE";
export const BETSHOP_LOADING_START = "BETSHOP_LOADING_START";
export const BETSHOP_LOADING_FAILURE = "BETSHOP_LOADING_FAILURE";

export const FILTERS_LOADING_DONE = "FILTERS_LOADING_DONE";
export const FILTERS_LOADING_START = "FILTERS_LOADING_START";
export const FILTERS_LOADING_FAILURE = "FILTERS_LOADING_FAILURE";

export const OPEN_PAYMENT_METHOD_FORM = "OPEN_PAYMENT_METHOD_FORM";
export const CLOSE_PAYMENT_METHOD_FORM = "CLOSE_PAYMENT_METHOD_FORM";
export const FILTER_PAYMENTS_FOR_USER_CURRENCY = "FILTER_PAYMENTS_FOR_USER_CURRENCY";
export const SET_EXTERNAL_FORM_DATA = "SET_EXTERNAL_FORM_DATA";
export const UNSET_EXTERNAL_FORM_DATA = "UNSET_EXTERNAL_FORM_DATA";
export const SET_METHOD_IFRAME_DATA = "SET_METHOD_IFRAME_DATA";
export const UNSET_METHOD_IFRAME_DATA = "UNSET_METHOD_IFRAME_DATA";
export const SET_METHOD_CONFIRM_ACTION = "SET_METHOD_CONFIRM_ACTION";
export const UNSET_METHOD_CONFIRM_ACTION = "UNSET_METHOD_CONFIRM_ACTION";
export const SET_DEPOSIT_NEXT_STEP = "SET_DEPOSIT_NEXT_STEP";
export const UNSET_DEPOSIT_NEXT_STEP = "UNSET_DEPOSIT_NEXT_STEP";

/*
* casino
*/

export const PROVIDERS_AND_CATEGORIES_LOADING_STARTED = "PROVIDERS_AND_CATEGORIES_LOADING_STARTED";
export const PROVIDERS_AND_CATEGORIES_LOADING_FAILED = "PROVIDERS_AND_CATEGORIES_LOADING_FAILED";
export const PROVIDERS_AND_CATEGORIES_LOADING_SUCCESS = "PROVIDERS_AND_CATEGORIES_LOADING_SUCCESS";

export const CASINO_GAMES_LOADING_STARED = "CASINO_GAMES_LOADING_STARED";
export const CASINO_GAMES_LOADING_FAILED = "CASINO_GAMES_LOADING_FAILED";
export const CASINO_GAMES_LOADING_SUCCESS = "CASINO_GAMES_LOADING_SUCCESS";

export const LIVE_CASINO_GAMES_LOADING_STARED = "LIVE_CASINO_GAMES_LOADING_STARED";
export const LIVE_CASINO_GAMES_LOADING_FAILED = "LIVE_CASINO_GAMES_LOADING_FAILED";
export const LIVE_CASINO_GAMES_LOADING_SUCCESS = "LIVE_CASINO_GAMES_LOADING_SUCCESS";

export const CASINO_GAMES_MOST_POPULAR_GAME_LOADING_STARED = "CASINO_GAMES_MOST_POPULAR_GAME_LOADING_STARED";
export const CASINO_GAMES_MOST_POPULAR_GAME_LOADING_FAILED = "CASINO_GAMES_MOST_POPULAR_GAME_LOADING_FAILED";
export const CASINO_GAMES_MOST_POPULAR_GAME_LOADING_SUCCESS = "CASINO_GAMES_MOST_POPULAR_GAME_LOADING_SUCCESS";

export const SELECT_CASINO_GAMES_CATEGORY = "SELECT_CASINO_GAMES_CATEGORY";
export const SELECT_CASINO_GAMES_PROVIDER = "SELECT_CASINO_GAMES_PROVIDER";
export const SELECT_LIVE_CASINO_GAMES_PROVIDER = "SELECT_LIVE_CASINO_GAMES_PROVIDER";

/*
 * messages
 */

export const DELETE_MESSAGE_BY_ID = "DELETE_MESSAGE_BY_ID";

/*
 * bet history filters
 */

export const SET_BET_HISTORY_FILTERS = "SET_BET_HISTORY_FILTERS";
export const RESET_BET_HISTORY_FILTERS = "RESET_BET_HISTORY_FILTERS";

/*
* hash params
* */

export const STORE_HASH_PARAMS = "STORE_HASH_PARAMS";
export const RESET_HASH_PARAMS = "RESET_HASH_PARAMS";
export const UPDATE_HASH_PARAMS = "UPDATE_HASH_PARAMS";

/*
 * virtual keyboard
 * */

export const TOGGLE_VIRTUAL_KEYBOARD = "TOGGLE_VIRTUAL_KEYBOARD";